/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { BlockType } from '../types';

export interface ComponentPreset {
  id: string;
  type: BlockType;
  name: string;
  nameFa: string;
  category: 'header' | 'bio' | 'skills' | 'stats' | 'socials' | 'multimedia' | 'content' | 'footer';
  categoryFa: 'سربرگ' | 'درباره من' | 'مهارت‌ها' | 'آمار گیت‌هاب' | 'شبکه‌های اجتماعی' | 'رسانه‌ها' | 'محتوا' | 'پاورقی';
  icon: string;
  description: string;
  descriptionFa: string;
  defaultProps: Record<string, any>;
}

export const COMPONENT_PRESETS: ComponentPreset[] = [
  // --- HEADERS & BANNERS ---
  {
    id: 'minimal-header',
    type: 'header',
    name: 'Minimal Clean Header',
    nameFa: 'سربرگ مینیمال',
    category: 'header',
    categoryFa: 'سربرگ',
    icon: 'User',
    description: 'A clean header with title, subtitle and alignment.',
    descriptionFa: 'یک سربرگ تمیز شامل عنوان، زیرعنوان و چینش دلخواه.',
    defaultProps: {
      title: "Hi, I'm ${username} 👋",
      subtitle: "A passionate Software Engineer specializing in modern web ecosystems.",
      align: 'center',
      paddingY: 2,
      marginY: 2,
    }
  },
  {
    id: 'cyber-header',
    type: 'header',
    name: 'Cyberpunk Banner Header',
    nameFa: 'سربرگ سایبرپانک',
    category: 'header',
    categoryFa: 'سربرگ',
    icon: 'Cpu',
    description: 'Header with neon colors and futuristic phrasing.',
    descriptionFa: 'سربرگ با رنگ‌های نئونی و جملات آینده‌نگرانه.',
    defaultProps: {
      title: "> CONST DEVELOPER = '${username}'",
      subtitle: "LOG: Building scalable, high-performance distributed solutions.",
      align: 'left',
      paddingY: 3,
      marginY: 2,
      capsuleText: 'CYBERPUNK_SYS',
      capsuleTheme: 'synthwave',
    }
  },
  {
    id: 'creative-banner',
    type: 'banner',
    name: 'Dynamic Capsule Banner',
    nameFa: 'بنر کپسول پویا',
    category: 'header',
    categoryFa: 'سربرگ',
    icon: 'Image',
    description: 'A stylish visual banner generated by Capsule Render.',
    descriptionFa: 'یک بنر بصری شیک تولید شده توسط Capsule Render.',
    defaultProps: {
      bannerUrl: 'https://capsule-render.vercel.app/api?type=waving&color=auto&height=180&section=header&text=Welcome%20to%20my%20Space&fontSize=45&animation=fadeIn',
      bannerHeight: 180,
      align: 'center',
    }
  },
  {
    id: 'custom-image-banner',
    type: 'banner',
    name: 'Custom Profile Banner',
    nameFa: 'بنر تصویر سفارشی',
    category: 'header',
    categoryFa: 'سربرگ',
    icon: 'Image',
    description: 'Embed your own custom hosting banner image.',
    descriptionFa: 'درج تصویر بنر سفارشی شما از لینک آدرس.',
    defaultProps: {
      bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&h=300&q=80',
      bannerHeight: 200,
      align: 'center',
    }
  },
  {
    id: 'typing-svg',
    type: 'typing',
    name: 'Animated Typing Subtitle',
    nameFa: 'زیرنویس تایپ متحرک',
    category: 'header',
    categoryFa: 'سربرگ',
    icon: 'Terminal',
    description: 'Typing text animation generated dynamically.',
    descriptionFa: 'انیمیشن متحرک تایپ متن که به صورت پویا ساخته می‌شود.',
    defaultProps: {
      typingLines: ['Frontend Architect', 'Creative Coder', 'Open Source Enthusiast'],
      typingSpeed: 400,
      typingColor: 'F50057',
      align: 'center',
    }
  },

  // --- BIO & ABOUT ---
  {
    id: 'developer-about',
    type: 'about',
    name: 'Full Stack Bio Grid',
    nameFa: 'بیوگرافی شبکه‌ای فول‌استک',
    category: 'bio',
    categoryFa: 'درباره من',
    icon: 'Briefcase',
    description: 'Structured bio layout answering work, learn, and collaboration.',
    descriptionFa: 'چیدمان بیوگرافی ساختاریافته شامل فعالیت‌ها، یادگیری‌ها و همکاری.',
    defaultProps: {
      title: 'About Me 🚀',
      aboutText: 'I am a highly driven Software Engineer focused on solving complex architectural problems.',
      workText: 'Building highly responsive SaaS web applications and cloud integrations.',
      learningText: 'Deep learning neural models and decentralized consensus protocols.',
      collabText: 'Innovative open-source frameworks and productivity extensions.',
      funFactText: 'I write code better when listening to 80s synthwave music!',
      align: 'left',
    }
  },
  {
    id: 'creative-quote',
    type: 'quote',
    name: 'Inspirational Callout/Quote',
    nameFa: 'نقل قول الهام‌بخش',
    category: 'bio',
    categoryFa: 'درباره من',
    icon: 'Quote',
    description: 'Render an elegant quote or motivational motto.',
    descriptionFa: 'نمایش یک نقل قول ظریف یا شعار انگیزشی با استایل مدرن.',
    defaultProps: {
      content: '“Programs must be written for people to read, and only incidentally for machines to execute.”',
      subtitle: 'Harold Abelson',
      align: 'center',
    }
  },

  // --- SKILLS & LANGUAGES ---
  {
    id: 'skills-badge-shield',
    type: 'skills',
    name: 'Tech Stack Badges',
    nameFa: 'نشان‌های پشته فناوری',
    category: 'skills',
    categoryFa: 'مهارت‌ها',
    icon: 'Code2',
    description: 'Dynamic shields.io badges representing coding languages.',
    descriptionFa: 'نشان‌های پویا از shields.io برای نمایش زبان‌های برنامه‌نویسی.',
    defaultProps: {
      title: 'Skills & Technologies 🛠️',
      skillsList: ['react', 'nextjs', 'typescript', 'nodejs', 'tailwindcss', 'mongodb', 'postgresql', 'docker'],
      skillsTheme: 'flat-square',
      align: 'center',
    }
  },
  {
    id: 'skill-icons-widget',
    type: 'skills',
    name: 'Dynamic Skill-Icons Grid',
    nameFa: 'شبکه نمادهای مهارت پویا',
    category: 'skills',
    categoryFa: 'مهارت‌ها',
    icon: 'Layers',
    description: 'Renders skill icons beautifully using skillicons.dev.',
    descriptionFa: 'نمایش آیکون‌های مهارت‌ها به شکلی شیک با ابزار skillicons.dev.',
    defaultProps: {
      title: 'Expertise 💻',
      skillsList: ['js', 'ts', 'react', 'next', 'tailwind', 'html', 'css', 'nodejs', 'git', 'docker', 'aws', 'python'],
      skillsTheme: 'flat', // can be flat or simple
      align: 'center',
    }
  },

  // --- STATS & GITHUB FEATURES ---
  {
    id: 'github-stats-card',
    type: 'stats',
    name: 'GitHub Profile Stats Card',
    nameFa: 'کارت آمار گیت‌هاب',
    category: 'stats',
    categoryFa: 'آمار گیت‌هاب',
    icon: 'LineChart',
    description: 'Visual display of commits, stars, PRs, and rank.',
    descriptionFa: 'نمایش بصری تعداد کامیت‌ها، ستاره‌ها، درخواست‌های ادغام و رتبه.',
    defaultProps: {
      title: 'GitHub Statistics 📊',
      githubUser: 'username',
      statsTheme: 'radical',
      showStats: true,
      showCommits: true,
      showPRs: true,
      showStars: true,
      showIssues: false,
      showContribs: true,
      hideRank: false,
      align: 'center',
    }
  },
  {
    id: 'github-top-langs',
    type: 'top_langs',
    name: 'Top Languages Card',
    nameFa: 'زبان‌های برنامه‌نویسی برتر',
    category: 'stats',
    categoryFa: 'آمار گیت‌هاب',
    icon: 'Code2',
    description: 'Visual chart of your most used languages on GitHub.',
    descriptionFa: 'نمودار بصری از پرکاربردترین زبان‌های شما در گیت‌هاب.',
    defaultProps: {
      title: 'Top Languages 📈',
      githubUser: 'username',
      statsTheme: 'radical',
      align: 'center',
    }
  },
  {
    id: 'visitor-badge',
    type: 'visitor_badge',
    name: 'Profile Visitor Counter',
    nameFa: 'شمارنده بازدیدکنندگان',
    category: 'stats',
    categoryFa: 'آمار گیت‌هاب',
    icon: 'Activity',
    description: 'Dynamic visitor tracker that increments on every page load.',
    descriptionFa: 'شمارنده پویای بازدید پروفایل که در هر بار لود صفحه افزایش می‌یابد.',
    defaultProps: {
      title: 'Profile Views 👀',
      githubUser: 'username',
      badgeColor: '007acc',
      badgeStyle: 'flat-square',
      badgeLabel: 'Visitors',
      align: 'center',
    }
  },
  {
    id: 'github-followers-badge',
    type: 'github_followers',
    name: 'Followers Badge',
    nameFa: 'نشان دنبال‌کنندگان گیت‌هاب',
    category: 'stats',
    categoryFa: 'آمار گیت‌هاب',
    icon: 'User',
    description: 'Displays your current GitHub follower count.',
    descriptionFa: 'نمایش زنده تعداد فالورهای گیت‌هاب شما.',
    defaultProps: {
      githubUser: 'username',
      badgeColor: '121212',
      badgeStyle: 'social',
      align: 'center',
    }
  },

  // --- SOCIALS & LINKS ---
  {
    id: 'social-links-grid',
    type: 'socials',
    name: 'Modern Social Buttons',
    nameFa: 'دکمه‌های شبکه‌های اجتماعی مدرن',
    category: 'socials',
    categoryFa: 'شبکه‌های اجتماعی',
    icon: 'Share2',
    description: 'Beautiful badges directing to your LinkedIn, Twitter, etc.',
    descriptionFa: 'نشان‌های زیبا برای هدایت کاربران به لینکدین، توییتر، یوتیوب و غیره.',
    defaultProps: {
      title: 'Connect With Me 🌐',
      socialLinks: [
        { platform: 'linkedin', username: 'yourname' },
        { platform: 'twitter', username: 'yourname' },
        { platform: 'medium', username: 'yourname' },
        { platform: 'youtube', username: 'yourchannel' },
      ],
      align: 'center',
    }
  },
  {
    id: 'custom-styled-buttons',
    type: 'buttons',
    name: 'Action CTA Buttons',
    nameFa: 'دکمه‌های اقدام (CTA)',
    category: 'socials',
    categoryFa: 'شبکه‌های اجتماعی',
    icon: 'Link2',
    description: 'Custom link buttons with colors and styles (e.g. Resume, Portfolio).',
    descriptionFa: 'دکمه‌های لینک دلخواه با رنگ و استایل سفارشی (مثلاً رزومه، پرتفولیو).',
    defaultProps: {
      customButtons: [
        { text: '🌐 View Portfolio', url: 'https://example.com', style: 'flat', color: '23D5AB' },
        { text: '📄 Download CV', url: 'https://example.com/resume.pdf', style: 'flat', color: 'E73C7E' },
      ],
      align: 'center',
    }
  },

  // --- MULTIMEDIA ---
  {
    id: 'spotify-widget',
    type: 'spotify',
    name: 'Spotify Playing Widget',
    nameFa: 'ویجت اسپاتیفای در حال پخش',
    category: 'multimedia',
    categoryFa: 'رسانه‌ها',
    icon: 'Music',
    description: 'Display currently listening to state on Spotify.',
    descriptionFa: 'نمایش زنده موسیقی در حال پخش شما در اسپاتیفای.',
    defaultProps: {
      title: 'Currently Listening To 🎵',
      githubUser: 'username',
      align: 'center',
    }
  },
  {
    id: 'youtube-widget',
    type: 'youtube',
    name: 'YouTube Video Embed',
    nameFa: 'جاسازی ویدیوی یوتیوب',
    category: 'multimedia',
    categoryFa: 'رسانه‌ها',
    icon: 'Youtube',
    description: 'Embed a custom YouTube video thumbnail/link beautifully.',
    descriptionFa: 'درج یک ویدیوی یوتیوب با تامبنیل و پیوند مناسب.',
    defaultProps: {
      title: 'Latest YouTube Video 📺',
      embedId: 'dQw4w9WgXcQ', // Default video ID
      align: 'center',
    }
  },

  // --- CONTENT & STRUCTURAL ---
  {
    id: 'project-showcase',
    type: 'projects',
    name: 'Featured Projects Card',
    nameFa: 'نمایش پروژه‌های برتر',
    category: 'content',
    categoryFa: 'محتوا',
    icon: 'Folder',
    description: 'A customizable list/grid of your best repositories or apps.',
    descriptionFa: 'لیست یا شبکه سفارشی از بهترین مخازن گیت‌هاب یا برنامه‌های شما.',
    defaultProps: {
      title: 'Featured Projects 📁',
      items: [
        {
          id: 'p1',
          title: 'Project Alpha 🚀',
          subtitle: 'React, TypeScript, Tailwind',
          description: 'A high-performance interactive web application built with modern standards.',
          link: 'https://github.com/username/project-alpha',
        },
        {
          id: 'p2',
          title: 'Project Beta 🧠',
          subtitle: 'Python, PyTorch, FastAPI',
          description: 'Autonomous multi-agent system reasoning engine utilizing visual LLMs.',
          link: 'https://github.com/username/project-beta',
        }
      ],
      align: 'left',
    }
  },
  {
    id: 'custom-experience',
    type: 'experience',
    name: 'Professional Timeline',
    nameFa: 'خط زمانی تجربه حرفه‌ای',
    category: 'content',
    categoryFa: 'محتوا',
    icon: 'Briefcase',
    description: 'Experience items with title, company, dates and descriptions.',
    descriptionFa: 'لیست تجربیات کاری با عنوان، شرکت، تاریخ‌ها و توضیحات.',
    defaultProps: {
      title: 'Experience History 💼',
      items: [
        {
          id: 'ex1',
          title: 'Lead Software Engineer',
          subtitle: 'Tech Global Corp • Full-time',
          date: '2024 - Present',
          description: 'Architecting ultra-low latency real-time APIs and core messaging services.',
        },
        {
          id: 'ex2',
          title: 'Frontend Developer',
          subtitle: 'InnoLabs Inc • Contract',
          date: '2022 - 2024',
          description: 'Reconstructed the client-side SPA state engines, improving page speeds by 40%.',
        }
      ],
      align: 'left',
    }
  },
  {
    id: 'code-snippet-block',
    type: 'code_block',
    name: 'Formatted Code Block',
    nameFa: 'بلوک کد فرمت‌شده',
    category: 'content',
    categoryFa: 'محتوا',
    icon: 'Terminal',
    description: 'Write customized, clean, syntax-highlighted code blocks.',
    descriptionFa: 'بلوک کد تمیز با زبان انتخابی خود برای پروفایل گیت‌هاب.',
    defaultProps: {
      title: 'Current Project Snippet 💻',
      language: 'typescript',
      content: `const developer = {
  name: "Arta Kolbadi",
  languages: ["TypeScript", "Python", "Go"],
  favoriteTech: ["React", "FastAPI", "Docker"],
  coffeeIn: "Infinite",
  codeOut: "Bugs-Free"
};`,
      align: 'left',
    }
  },
  {
    id: 'info-callout',
    type: 'callout',
    name: 'Alert/Info Callout Box',
    nameFa: 'بلوک هشدار یا نکته',
    category: 'content',
    categoryFa: 'محتوا',
    icon: 'HelpCircle',
    description: 'High visibility boxed callouts in GitHub style.',
    descriptionFa: 'کادرهای برجسته اطلاع‌رسانی، نکته یا هشدار به سبک گیت‌هاب.',
    defaultProps: {
      title: 'Current Status 📍',
      calloutType: 'tip',
      content: 'I am currently looking for senior freelance or full-time remote opportunities! Feel free to reach out via email.',
      align: 'left',
    }
  },

  // --- FOOTER ---
  {
    id: 'profile-footer',
    type: 'footer',
    name: 'Interactive Profile Footer',
    nameFa: 'پاورقی تعاملی پروفایل',
    category: 'footer',
    categoryFa: 'پاورقی',
    icon: 'Award',
    description: 'Complete the profile README with a subtle sign-off.',
    descriptionFa: 'پایان‌بخش فایل خواندنی پروفایل با یک امضا یا متن تشکر.',
    defaultProps: {
      content: '⭐️ Thanks for visiting my profile! Please leave a star if you liked my projects.',
      align: 'center',
    }
  }
];

// List of all popular skills to make selection in badges & skills grids super rich
export const POPULAR_SKILLS = [
  { id: 'react', name: 'React', color: '61DAFB', logo: 'react' },
  { id: 'nextjs', name: 'Next.js', color: '000000', logo: 'nextdotjs' },
  { id: 'typescript', name: 'TypeScript', color: '3178C6', logo: 'typescript' },
  { id: 'javascript', name: 'JavaScript', color: 'F7DF1E', logo: 'javascript' },
  { id: 'nodejs', name: 'Node.js', color: '339933', logo: 'nodedotjs' },
  { id: 'tailwindcss', name: 'TailwindCSS', color: '06B6D4', logo: 'tailwindcss' },
  { id: 'python', name: 'Python', color: '3776AB', logo: 'python' },
  { id: 'golang', name: 'Go', color: '00ADD8', logo: 'go' },
  { id: 'rust', name: 'Rust', color: '000000', logo: 'rust' },
  { id: 'postgresql', name: 'PostgreSQL', color: '4169E1', logo: 'postgresql' },
  { id: 'mongodb', name: 'MongoDB', color: '47A248', logo: 'mongodb' },
  { id: 'docker', name: 'Docker', color: '2496ED', logo: 'docker' },
  { id: 'aws', name: 'AWS', color: '232F3E', logo: 'amazonwebservices' },
  { id: 'git', name: 'Git', color: 'F05032', logo: 'git' },
  { id: 'html', name: 'HTML5', color: 'E34F26', logo: 'html5' },
  { id: 'css', name: 'CSS3', color: '1572B6', logo: 'css3' },
  { id: 'sass', name: 'Sass', color: 'CC6699', logo: 'sass' },
  { id: 'vue', name: 'Vue.js', color: '4FC08D', logo: 'vuedotjs' },
  { id: 'angular', name: 'Angular', color: 'DD0031', logo: 'angular' },
  { id: 'graphql', name: 'GraphQL', color: 'E10098', logo: 'graphql' },
  { id: 'prisma', name: 'Prisma', color: '2D3748', logo: 'prisma' },
  { id: 'firebase', name: 'Firebase', color: 'FFCA28', logo: 'firebase' },
  { id: 'supabase', name: 'Supabase', color: '3ECF8E', logo: 'supabase' },
  { id: 'kubernetes', name: 'Kubernetes', color: '326CE5', logo: 'kubernetes' },
  { id: 'linux', name: 'Linux', color: 'FCC624', logo: 'linux' },
  { id: 'figma', name: 'Figma', color: 'F24E1E', logo: 'figma' },
];
